In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np

In [3]:
# df_graph = merged_df.loc[merged_df['LABEL_LVL_1_DESC'] == desc_list[0]]
# # df_graph = df_graph.sort_values('PROGRAM_PERCENT', ascending = False)
# # df_graph = df_graph.loc[df_graph['PROGRAM_PERCENT'] != df_graph['PROGRAM_PERCENT'].min()]
# # df_graph = boston_df_o[(z < 3).all(axis=1)]
# # df_graph.plot.line(x = 'PROGRAM_PERCENT', y = 'Percent')

def graph_percent(df, description,indicator):
    df_graph = df.loc[merged_df['TEST_CMPNT_TYP_NM'] == description]
    z = (stats.zscore(df_graph.loc[indicator]))
    df_graph.loc[:,(f'{description}_zscore')] = z
    df_clean = df_graph.loc[(df_graph[f'{description}_zscore']<2) & (df_graph[f'{description}_zscore']>-2)]
    df_clean.sort_values(indicator, ascending = False).plot.scatter(x = indicator, y = 'Percent')
    x_values = df_clean[indicator]
    y_values = df_clean['Percent']
    (slope, intercept, rvalue, pvalue, stderr) = stats.linregress(x_values, y_values)
    regress_values = x_values * slope + intercept
    line_eq = "y = " + str(round(slope,2)) + "x +" + str(round(intercept,2))
    print(line_eq)
    plt.plot(x_values, regress_values)
    plt.title(f'{description} vs Percent Enrollment({indicator})')
    plt.ylabel(f'Percent Enrollment')
    print(f'p-value: {pvalue}, std error: {stderr}')


# from sklearn import preprocessing
# df_graph
# x = df_graph[['PROGRAM_PERCENT','Percent']].values #returns a numpy array
# min_max_scaler = preprocessing.MinMaxScaler()
# x_scaled = min_max_scaler.fit_transform(x)
# x_scaled
# df_graph.loc[:,['Program_percent_scaled','Percent_scaled']] = x_scaled
# df_graph.sort_values('Program_percent_scaled', ascending = False).plot.line(x ='Program_percent_scaled', y= 'Percent_scaled' )

In [4]:
type_group_df = pd.read_csv('../data_export/type_group_EOC.csv')
school_df = pd.read_csv('../data_export/school_clean.csv')

In [5]:
type_group_df = type_group_df.drop(columns=['Unnamed: 0']).rename(columns={
    'SCHOOL_DISTRCT_CD':'School District Code'
})

In [6]:
type_group_df = type_group_df.loc[type_group_df['School District Code'] != 'ALL']
type_group_df['School District Code'] = type_group_df['School District Code'].astype(int)
# type_group_df['School District Code'] = type_group_df['School District Code'].astype(int)
type_group_df

,School District Code,TEST_CMPNT_TYP_NM,ACDMC_LVL,BEGIN_PCT,DEVELOPING_PCT,PROFICIENT_PCT,DISTINGUISHED_PCT
0,601,9th Grade Literature and Composition,9.400000,19.733333,36.633333,35.225000,8.416667
1,601,Algebra I,9.640000,29.439130,43.404348,23.039130,4.126087
2,601,American Literature and Composition,10.684211,38.905556,32.005556,22.272222,6.827778
3,601,Biology,9.562500,28.260000,23.393333,38.006667,10.340000
4,601,Economics/Business/Free Enterprise,11.785714,18.675000,32.041667,39.775000,9.525000
...,...,...,...,...,...,...,...
1624,891,Biology,9.703704,91.273529,7.873529,0.861765,0.000000
1625,891,Coordinate Algebra,9.263158,93.489655,6.513793,0.000000,0.000000
1626,891,Economics/Business/Free Enterprise,11.424242,76.105556,12.355556,11.516667,0.000000
1627,891,Physical Science,10.176471,90.630769,9.369231,0.000000,0.000000
1628,891,US History,10.750000,71.607143,25.950000,2.414286,0.000000

In [11]:
merged_df = pd.merge(school_df,type_group_df, on = 'School District Code', how = 'inner')
merged_df.loc[merged_df['TEST_CMPNT_TYP_NM']==0]
merged_df

,School Year,School District Code,School District Name,School Code,School Name,Graduates,Postsecondary Institution,Percent,TEST_CMPNT_TYP_NM,ACDMC_LVL,BEGIN_PCT,DEVELOPING_PCT,PROFICIENT_PCT,DISTINGUISHED_PCT
0,2017,601,Appling County,ALL,All Schools,198.0,118.0,59.6,9th Grade Literature and Composition,9.400000,19.733333,36.633333,35.225000,8.416667
1,2017,601,Appling County,ALL,All Schools,198.0,118.0,59.6,Algebra I,9.640000,29.439130,43.404348,23.039130,4.126087
2,2017,601,Appling County,ALL,All Schools,198.0,118.0,59.6,American Literature and Composition,10.684211,38.905556,32.005556,22.272222,6.827778
3,2017,601,Appling County,ALL,All Schools,198.0,118.0,59.6,Biology,9.562500,28.260000,23.393333,38.006667,10.340000
4,2017,601,Appling County,ALL,All Schools,198.0,118.0,59.6,Economics/Business/Free Enterprise,11.785714,18.675000,32.041667,39.775000,9.525000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1502,2017,891,Department of Juvenile Justice,ALL,All Schools,20.0,10.0,50.0,Biology,9.703704,91.273529,7.873529,0.861765,0.000000
1503,2017,891,Department of Juvenile Justice,ALL,All Schools,20.0,10.0,50.0,Coordinate Algebra,9.263158,93.489655,6.513793,0.000000,0.000000
1504,2017,891,Department of Juvenile Justice,ALL,All Schools,20.0,10.0,50.0,Economics/Business/Free Enterprise,11.424242,76.105556,12.355556,11.516667,0.000000
1505,2017,891,Department of Juvenile Justice,ALL,All Schools,20.0,10.0,50.0,Physical Science,10.176471,90.630769,9.369231,0.000000,0.000000
1506,2017,891,Department of Juvenile Justice,ALL,All Schools,20.0,10.0,50.0,US History,10.750000,71.607143,25.950000,2.414286,0.000000

In [9]:
type_group_df['TEST_CMPNT_TYP_NM'].unique()

array(['9th Grade Literature and Composition', 'Algebra I',
       'American Literature and Composition', 'Biology',
       'Economics/Business/Free Enterprise', 'Geometry',
       'Physical Science', 'US History', 'Analytic Geometry',
       'Coordinate Algebra'], dtype=object)

In [69]:
# for test in type_group_df['TEST_CMPNT_TYP_NM'].unique():
#     try:
#         graph_percent(merged_df, test, 'DEVELOPING_PCT')
#     except: 
#         print(f'the test {test} is empty')

# graph_percent(merged_df, 'Algebra I', 'DEVELOPING_PCT')

merged_df

1       43.404348
9       39.863636
18      52.214286
26      47.991667
34      31.296154
          ...
1456    36.383333
1465    18.486667
1475    20.733333
1483    26.714141
1492    36.747368
Name: DEVELOPING_PCT, Length: 165, dtype: float64